import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/Header";
import Main from "@/components/layout/Main";
import Providers from "./providers";
import ThemeProviders from "@/components/providers/ThemeProvider";

const BeaufortforLoL = localFont({
  src: [
    {
      path: "../style/fonts/BeaufortforLOL-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../style/fonts/BeaufortforLOL-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../style/fonts/BeaufortforLOL-Light.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-beaufort-sans",
});

export const metadata: Metadata = {
  title: "League of Legends",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={"ko"} suppressHydrationWarning>
      <body className={`${BeaufortforLoL.variable} antialiased`}>
        <Providers>
          <ThemeProviders>
            <Header />
            <Main>{children}</Main>
          </ThemeProviders>
        </Providers>
      </body>
    </html>
  );
}
